### PR TITLE
Retry for failed jobs (#29)

### PR DESCRIPTION
**Pull request by chrisjensen**
This PR adds support for automatic retry of failed jobs (#29)  if the error object returned via `done(err)` has a `shouldRetry` property that is truthy.
(allowing the job to differentiate between a soft fail and a hard fail)

The jobs are retried using exponential backoff. The delay until the next retry is stored in a new column `retryIn`.

### CODE REVIEW

**Comment by timgit** [comment]
👍 Thanks for this!  Reviewing...

**Comment by timgit** [comment]
I owe you a response on this.  :)  I don't think this PR is compatible with what I'm wanting to do with #29. My plans for failure handling are to consolidate it with expiration so expiration can simply become a failure type.  

Also, I have a philosophical disagreement on forcing the the job handler (or `fail()` api) to control this via something like a `shouldRetry` property on an error object.  My preference for configuring things like retries, expiration, throttling, etc. is to use the `publish()` api with options so no downstream logic is required in handlers.

However, there's also a good chance I'm just not considering your specific use case as well.  😁

**Comment by chrisjensen** [comment]
Sorry for the slow reply over Christmas period. The reason I'm using a flag on the exception is we have different exceptional circumstances that come up, some should retry, some should definitely not, so a flag on publish isn't nuanced enough for our needs.
I opted for shouldRetry because it's least breaking - in existing implementations the flag would be missing so no behaviour change.
(It also means the code handling the exception doesn't need to know how to do job re-queueing so it's easier to separate concerns)

Happy to revise this patch for other ways to resolve this that allow the type of failure to determine if the job is retried.

**Comment by timgit** [comment]
Chris, no worries.  😁 

If the retry itself is conditional, I'm persuaded that it should be handled either in the handler itself (just do another publish() with `job.name` and `job.data`, for example), or via `onFail()`/`onExpire()` if the publish logic needs to be kept out of the handler for logic consolidation purposes.  I have a couple use cases like this, and typically colocate a `onFail()` and `publish()` call at the origin/orchestrator.

**Comment by timgit** [comment]
Chris, I just published a beta for 3.0 that addresses retry on fail.  If you have a chance and you're still keen on this, please give it a try and let me know your thoughts.

Thanks!

**Comment by chrisjensen** [comment]
Thanks Tim, sorry I didn't follow up. We're under the pump a bit at the moment, but hopefully in a few weeks I may have time to come back and check this out.
For the moment we went along the lines of your suggestion: we've wrapped our jobs in a handler that will fail the job if its a hard fail, but let it expire if it's a soft failure so that the expire retry regime takes over.

**Pull request closed without merging**
