### PR TITLE
use batchSize for batch subscription

### PR DESCRIPTION
**Pull request by haoliangyu**
This is the implementation of batch subscription (PR #45)

@timgit Please review the code and I will update the documentation once the code is approved.

### CODE REVIEW

**Comment by timgit** [comment]
Thanks for this. I think the tests are failing because teamSize or batchSize are both optional.  But I think we're on the same page in regards to intent.  Also, I'm hesitant to do batch completion on them as well.  Do you have a strong opinion on that?

**Comment by haoliangyu** [comment]
As for the batch completion, it does have the risk of not completing all jobs because some rows are locked for other operations, as mentioned in the documentation. Is that your concern? I personally don't have a strong opinion or answer on how to do it. Maybe just not provide the complete function and instruct the user to complete jobs manually?

Also, I do have a concern about updating the meaning of `teamSize` and `batchSize` as they are the same in the current version. In my use case, I have been using `batchSize` but many other people may be using `teamSize`. Therefore this PR should be part of the next major update because of the breaking change. So it is a right time to do it? I am fine with deferring the PR. BTW, my initial thought was to introduce a flag like `batchProcessing=true/false`.

**Comment by timgit** [comment]
Yeah, the [subscribe config docs](https://github.com/timgit/pg-boss/blob/master/docs/configuration.md#subscribe-options) show them both.  I forgot that I was so verbose there, lol.  Ok, yeah, that's unfortunate for those who are shy of majors.  👍 

I have a list of things that merit a major, regardless.  Seems like a good time here in a month or 2.

**Comment by haoliangyu** [comment]
@timgit 

The code is updated to 
* to use `teamSize` by default unless `batchSize`is specified, which satisfies current tests
* add an example at the documentation

**Pull request closed without merging**
